<?php

namespace DevFighters\Utils\Domain\Enum;

use DevFighters\Utils\Domain\Trait\Enum\RandomEnumTrait;

/**
 * @method static self[] cases()  Retourne tous les cas de l'énumération
 */
enum AppCurrencyEnum: int
{
    use RandomEnumTrait;

    case EUR = 1;   // Euro
    case USD = 2;   // US Dollar
    case GBP = 3;   // British Pound
    case THB = 4;   // Thai Baht
    case JPY = 5;   // Japanese Yen
    case CHF = 6;   // Swiss Franc
    case CAD = 7;   // Canadian Dollar
    case AUD = 8;   // Australian Dollar
    case NZD = 9;   // New Zealand Dollar
    case CNY = 10;  // Chinese Yuan (Renminbi)
    case HKD = 11;  // Hong Kong Dollar
    case SGD = 12;  // Singapore Dollar
    case INR = 13;  // Indian Rupee
    case KRW = 14;  // South Korean Won
    case SEK = 15;  // Swedish Krona
    case NOK = 16;  // Norwegian Krone
    case DKK = 17;  // Danish Krone
    case PLN = 18;  // Polish Zloty
    case CZK = 19;  // Czech Koruna
    case HUF = 20;  // Hungarian Forint
    case MXN = 21;  // Mexican Peso
    case BRL = 22;  // Brazilian Real
    case ZAR = 23;  // South African Rand
    case AED = 24;  // UAE Dirham
    case SAR = 25;  // Saudi Riyal
    case TRY = 26;  // Turkish Lira
    case ILS = 27;  // Israeli Shekel
    case EGP = 28;  // Egyptian Pound
    case IDR = 29;  // Indonesian Rupiah
    case PHP = 30;  // Philippine Peso
    case MYR = 31;  // Malaysian Ringgit
    case VND = 32;  // Vietnamese Dong
    case ARS = 33;  // Argentine Peso
    case CLP = 34;  // Chilean Peso
    case COP = 35;  // Colombian Peso
    case RON = 36;  // Romanian Leu
    case BGN = 37;  // Bulgarian Lev
    case HRK = 38;  // Croatian Kuna (legacy)
    case ISK = 39;  // Icelandic Krona
    case MAD = 40;  // Moroccan Dirham
    case AFN = 41;  // Afghan Afghani
    case ALL = 42;  // Albanian Lek
    case AMD = 43;  // Armenian Dram
    case ANG = 44;  // Netherlands Antillean Guilder
    case AOA = 45;  // Angolan Kwanza
    case AWG = 46;  // Aruban Florin
    case AZN = 47;  // Azerbaijani Manat
    case BAM = 48;  // Bosnia-Herzegovina Convertible Mark
    case BBD = 49;  // Barbadian Dollar
    case BDT = 50;  // Bangladeshi Taka
    case BHD = 51;  // Bahraini Dinar
    case BIF = 52;  // Burundian Franc
    case BMD = 53;  // Bermudian Dollar
    case BND = 54;  // Brunei Dollar
    case BOB = 55;  // Bolivian Boliviano
    case BSD = 56;  // Bahamian Dollar
    case BTN = 57;  // Bhutanese Ngultrum
    case BWP = 58;  // Botswanan Pula
    case BYN = 59;  // Belarusian Ruble
    case BZD = 60;  // Belize Dollar
    case CDF = 61;  // Congolese Franc
    case CRC = 62;  // Costa Rican Colón
    case CUP = 63;  // Cuban Peso
    case CVE = 64;  // Cape Verdean Escudo
    case DJF = 65;  // Djiboutian Franc
    case DOP = 66;  // Dominican Peso
    case DZD = 67;  // Algerian Dinar
    case ERN = 68;  // Eritrean Nakfa
    case ETB = 69;  // Ethiopian Birr
    case FJD = 70;  // Fijian Dollar
    case FKP = 71;  // Falkland Islands Pound
    case GEL = 72;  // Georgian Lari
    case GHS = 73;  // Ghanaian Cedi
    case GIP = 74;  // Gibraltar Pound
    case GMD = 75;  // Gambian Dalasi
    case GNF = 76;  // Guinean Franc
    case GTQ = 77;  // Guatemalan Quetzal
    case GYD = 78;  // Guyanese Dollar
    case HNL = 79;  // Honduran Lempira
    case HTG = 80;  // Haitian Gourde
    case IQD = 81;  // Iraqi Dinar
    case IRR = 82;  // Iranian Rial
    case JMD = 83;  // Jamaican Dollar
    case JOD = 84;  // Jordanian Dinar
    case KES = 85;  // Kenyan Shilling
    case KGS = 86;  // Kyrgyzstani Som
    case KHR = 87;  // Cambodian Riel
    case KMF = 88;  // Comorian Franc
    case KWD = 89;  // Kuwaiti Dinar
    case KYD = 90;  // Cayman Islands Dollar
    case KZT = 91;  // Kazakhstani Tenge
    case LAK = 92;  // Lao Kip
    case LBP = 93;  // Lebanese Pound
    case LKR = 94;  // Sri Lankan Rupee
    case LRD = 95;  // Liberian Dollar
    case LSL = 96;  // Lesotho Loti
    case LYD = 97;  // Libyan Dinar
    case MDL = 98;  // Moldovan Leu
    case MGA = 99;  // Malagasy Ariary
    case MKD = 100; // Macedonian Denar
    case MMK = 101; // Myanmar Kyat
    case MNT = 102; // Mongolian Tögrög
    case MOP = 103; // Macanese Pataca
    case MRU = 104; // Mauritanian Ouguiya
    case MUR = 105; // Mauritian Rupee
    case MVR = 106; // Maldivian Rufiyaa
    case MWK = 107; // Malawian Kwacha
    case MZN = 108; // Mozambican Metical
    case NAD = 109; // Namibian Dollar
    case NGN = 110; // Nigerian Naira
    case NIO = 111; // Nicaraguan Córdoba
    case NPR = 112; // Nepalese Rupee
    case OMR = 113; // Omani Rial
    case PAB = 114; // Panamanian Balboa
    case PEN = 115; // Peruvian Sol
    case PGK = 116; // Papua New Guinean Kina
    case PKR = 117; // Pakistani Rupee
    case PYG = 118; // Paraguayan Guarani
    case QAR = 119; // Qatari Riyal
    case RSD = 120; // Serbian Dinar
    case RUB = 121; // Russian Ruble
    case RWF = 122; // Rwandan Franc
    case SBD = 123; // Solomon Islands Dollar
    case SCR = 124; // Seychellois Rupee
    case SDG = 125; // Sudanese Pound
    case SHP = 126; // Saint Helena Pound
    case SLE = 127; // Sierra Leonean Leone
    case SOS = 128; // Somali Shilling
    case SRD = 129; // Surinamese Dollar
    case SSP = 130; // South Sudanese Pound
    case STN = 131; // São Tomé and Príncipe Dobra
    case SYP = 132; // Syrian Pound
    case SZL = 133; // Swazi Lilangeni
    case TJS = 134; // Tajikistani Somoni
    case TMT = 135; // Turkmenistan Manat
    case TND = 136; // Tunisian Dinar
    case TOP = 137; // Tongan Paʻanga
    case TTD = 138; // Trinidad and Tobago Dollar
    case TWD = 139; // New Taiwan Dollar
    case TZS = 140; // Tanzanian Shilling
    case UAH = 141; // Ukrainian Hryvnia
    case UGX = 142; // Ugandan Shilling
    case UYU = 143; // Uruguayan Peso
    case UZS = 144; // Uzbekistani Som
    case VES = 145; // Venezuelan Bolívar
    case VUV = 146; // Vanuatu Vatu
    case WST = 147; // Samoan Tala
    case XAF = 148; // Central African CFA Franc
    case XCD = 149; // East Caribbean Dollar
    case XOF = 150; // West African CFA Franc
    case XPF = 151; // CFP Franc
    case YER = 152; // Yemeni Rial
    case ZMW = 153; // Zambian Kwacha

    public function name(): string
    {
        return match ($this) {
            self::EUR => 'euro',
            self::USD => 'us dollar',
            self::GBP => 'pound sterling',
            self::THB => 'thai baht',
            self::JPY => 'japanese yen',
            self::CHF => 'swiss franc',
            self::CAD => 'canadian dollar',
            self::AUD => 'australian dollar',
            self::NZD => 'new zealand dollar',
            self::CNY => 'chinese yuan',
            self::HKD => 'hong kong dollar',
            self::SGD => 'singapore dollar',
            self::INR => 'indian rupee',
            self::KRW => 'south korean won',
            self::SEK => 'swedish krona',
            self::NOK => 'norwegian krone',
            self::DKK => 'danish krone',
            self::PLN => 'polish zloty',
            self::CZK => 'czech koruna',
            self::HUF => 'hungarian forint',
            self::MXN => 'mexican peso',
            self::BRL => 'brazilian real',
            self::ZAR => 'south african rand',
            self::AED => 'uae dirham',
            self::SAR => 'saudi riyal',
            self::TRY => 'turkish lira',
            self::ILS => 'israeli shekel',
            self::EGP => 'egyptian pound',
            self::IDR => 'indonesian rupiah',
            self::PHP => 'philippine peso',
            self::MYR => 'malaysian ringgit',
            self::VND => 'vietnamese dong',
            self::ARS => 'argentine peso',
            self::CLP => 'chilean peso',
            self::COP => 'colombian peso',
            self::RON => 'romanian leu',
            self::BGN => 'bulgarian lev',
            self::HRK => 'croatian kuna',
            self::ISK => 'icelandic krona',
            self::MAD => 'moroccan dirham',
            self::AFN => 'afghan afghani',
            self::ALL => 'albanian lek',
            self::AMD => 'armenian dram',
            self::ANG => 'netherlands antillean guilder',
            self::AOA => 'angolan kwanza',
            self::AWG => 'aruban florin',
            self::AZN => 'azerbaijani manat',
            self::BAM => 'convertible mark',
            self::BBD => 'barbadian dollar',
            self::BDT => 'bangladeshi taka',
            self::BHD => 'bahraini dinar',
            self::BIF => 'burundian franc',
            self::BMD => 'bermudian dollar',
            self::BND => 'brunei dollar',
            self::BOB => 'bolivian boliviano',
            self::BSD => 'bahamian dollar',
            self::BTN => 'bhutanese ngultrum',
            self::BWP => 'botswana pula',
            self::BYN => 'belarusian ruble',
            self::BZD => 'belize dollar',
            self::CDF => 'congolese franc',
            self::CRC => 'costa rican colón',
            self::CUP => 'cuban peso',
            self::CVE => 'cape verdean escudo',
            self::DJF => 'djiboutian franc',
            self::DOP => 'dominican peso',
            self::DZD => 'algerian dinar',
            self::ERN => 'eritrean nakfa',
            self::ETB => 'ethiopian birr',
            self::FJD => 'fijian dollar',
            self::FKP => 'falkland islands pound',
            self::GEL => 'georgian lari',
            self::GHS => 'ghanaian cedi',
            self::GIP => 'gibraltar pound',
            self::GMD => 'gambian dalasi',
            self::GNF => 'guinean franc',
            self::GTQ => 'guatemalan quetzal',
            self::GYD => 'guyanese dollar',
            self::HNL => 'honduran lempira',
            self::HTG => 'haitian gourde',
            self::IQD => 'iraqi dinar',
            self::IRR => 'iranian rial',
            self::JMD => 'jamaican dollar',
            self::JOD => 'jordanian dinar',
            self::KES => 'kenyan shilling',
            self::KGS => 'kyrgyzstani som',
            self::KHR => 'cambodian riel',
            self::KMF => 'comorian franc',
            self::KWD => 'kuwaiti dinar',
            self::KYD => 'cayman islands dollar',
            self::KZT => 'kazakhstani tenge',
            self::LAK => 'lao kip',
            self::LBP => 'lebanese pound',
            self::LKR => 'sri lankan rupee',
            self::LRD => 'liberian dollar',
            self::LSL => 'lesotho loti',
            self::LYD => 'libyan dinar',
            self::MDL => 'moldovan leu',
            self::MGA => 'malagasy ariary',
            self::MKD => 'macedonian denar',
            self::MMK => 'myanmar kyat',
            self::MNT => 'mongolian tögrög',
            self::MOP => 'macanese pataca',
            self::MRU => 'mauritanian ouguiya',
            self::MUR => 'mauritian rupee',
            self::MVR => 'maldivian rufiyaa',
            self::MWK => 'malawian kwacha',
            self::MZN => 'mozambican metical',
            self::NAD => 'namibian dollar',
            self::NGN => 'nigerian naira',
            self::NIO => 'nicaraguan córdoba',
            self::NPR => 'nepalese rupee',
            self::OMR => 'omani rial',
            self::PAB => 'panamanian balboa',
            self::PEN => 'peruvian sol',
            self::PGK => 'papua new guinean kina',
            self::PKR => 'pakistani rupee',
            self::PYG => 'paraguayan guarani',
            self::QAR => 'qatari riyal',
            self::RSD => 'serbian dinar',
            self::RUB => 'russian ruble',
            self::RWF => 'rwandan franc',
            self::SBD => 'solomon islands dollar',
            self::SCR => 'seychellois rupee',
            self::SDG => 'sudanese pound',
            self::SHP => 'saint helena pound',
            self::SLE => 'sierra leonean leone',
            self::SOS => 'somali shilling',
            self::SRD => 'surinamese dollar',
            self::SSP => 'south sudanese pound',
            self::STN => 'são tomé and príncipe dobra',
            self::SYP => 'syrian pound',
            self::SZL => 'swazi lilangeni',
            self::TJS => 'tajikistani somoni',
            self::TMT => 'turkmenistani manat',
            self::TND => 'tunisian dinar',
            self::TOP => 'tongan paʻanga',
            self::TTD => 'trinidad and tobago dollar',
            self::TWD => 'new taiwan dollar',
            self::TZS => 'tanzanian shilling',
            self::UAH => 'ukrainian hryvnia',
            self::UGX => 'ugandan shilling',
            self::UYU => 'uruguayan peso',
            self::UZS => 'uzbekistani som',
            self::VES => 'venezuelan bolívar',
            self::VUV => 'vanuatu vatu',
            self::WST => 'samoan tala',
            self::XAF => 'central african cfa franc',
            self::XCD => 'east caribbean dollar',
            self::XOF => 'west african cfa franc',
            self::XPF => 'cfp franc',
            self::YER => 'yemeni rial',
            self::ZMW => 'zambian kwacha',
        };
    }

    public function symbol(): string
    {
        return match ($this) {
            self::EUR => '€',
            self::USD => '$',
            self::GBP => '£',
            self::THB => '฿',
            self::JPY => '¥',
            self::CHF => 'CHF',
            self::CAD => 'CA$',
            self::AUD => 'A$',
            self::NZD => 'NZ$',
            self::CNY => '¥',
            self::HKD => 'HK$',
            self::SGD => 'S$',
            self::INR => '₹',
            self::KRW => '₩',
            self::SEK => 'kr',
            self::NOK => 'kr',
            self::DKK => 'kr',
            self::PLN => 'zł',
            self::CZK => 'Kč',
            self::HUF => 'Ft',
            self::MXN => '$',
            self::BRL => 'R$',
            self::ZAR => 'R',
            self::AED => 'د.إ',
            self::SAR => '﷼',
            self::TRY => '₺',
            self::ILS => '₪',
            self::EGP => '£',
            self::IDR => 'Rp',
            self::PHP => '₱',
            self::MYR => 'RM',
            self::VND => '₫',
            self::ARS => '$',
            self::CLP => '$',
            self::COP => '$',
            self::RON => 'lei',
            self::BGN => 'лв',
            self::HRK => 'kn',
            self::ISK => 'kr',
            self::MAD => 'د.م.',
            self::AFN => '؋',
            self::ALL => 'L',
            self::AMD => '֏',
            self::ANG => 'ƒ',
            self::AOA => 'Kz',
            self::AWG => 'ƒ',
            self::AZN => '₼',
            self::BAM => 'KM',
            self::BBD => '$',
            self::BDT => '৳',
            self::BHD => '.د.ب',
            self::BIF => 'Fr',
            self::BMD => '$',
            self::BND => '$',
            self::BOB => 'Bs.',
            self::BSD => '$',
            self::BTN => 'Nu.',
            self::BWP => 'P',
            self::BYN => 'Br',
            self::BZD => '$',
            self::CDF => 'Fr',
            self::CRC => '₡',
            self::CUP => '$',
            self::CVE => '$',
            self::DJF => 'Fr',
            self::DOP => '$',
            self::DZD => 'د.ج',
            self::ERN => 'Nfk',
            self::ETB => 'Br',
            self::FJD => '$',
            self::FKP => '£',
            self::GEL => '₾',
            self::GHS => '₵',
            self::GIP => '£',
            self::GMD => 'D',
            self::GNF => 'Fr',
            self::GTQ => 'Q',
            self::GYD => '$',
            self::HNL => 'L',
            self::HTG => 'G',
            self::IQD => 'ع.د',
            self::IRR => '﷼',
            self::JMD => '$',
            self::JOD => 'د.ا',
            self::KES => 'Sh',
            self::KGS => 'сом',
            self::KHR => '៛',
            self::KMF => 'Fr',
            self::KWD => 'د.ك',
            self::KYD => '$',
            self::KZT => '₸',
            self::LAK => '₭',
            self::LBP => '£',
            self::LKR => 'Rs',
            self::LRD => '$',
            self::LSL => 'L',
            self::LYD => 'ل.د',
            self::MDL => 'L',
            self::MGA => 'Ar',
            self::MKD => 'ден',
            self::MMK => 'Ks',
            self::MNT => '₮',
            self::MOP => 'P',
            self::MRU => 'UM',
            self::MUR => '₨',
            self::MVR => 'Rf',
            self::MWK => 'MK',
            self::MZN => 'MT',
            self::NAD => '$',
            self::NGN => '₦',
            self::NIO => 'C$',
            self::NPR => '₨',
            self::OMR => 'ر.ع',
            self::PAB => 'B/.',
            self::PEN => 'S/',
            self::PGK => 'K',
            self::PKR => '₨',
            self::PYG => '₲',
            self::QAR => 'ر.ق',
            self::RSD => 'дин',
            self::RUB => '₽',
            self::RWF => 'Fr',
            self::SBD => '$',
            self::SCR => '₨',
            self::SDG => '£',
            self::SHP => '£',
            self::SLE => 'Le',
            self::SOS => 'Sh',
            self::SRD => '$',
            self::SSP => '£',
            self::STN => 'Db',
            self::SYP => '£',
            self::SZL => 'L',
            self::TJS => 'ЅМ',
            self::TMT => 'm',
            self::TND => 'د.ت',
            self::TOP => 'T$',
            self::TTD => '$',
            self::TWD => 'NT$',
            self::TZS => 'Sh',
            self::UAH => '₴',
            self::UGX => 'Sh',
            self::UYU => '$',
            self::UZS => 'soʻm',
            self::VES => 'Bs.',
            self::VUV => 'Vt',
            self::WST => 'T',
            self::XAF => 'Fr',
            self::XCD => '$',
            self::XOF => 'Fr',
            self::XPF => '₣',
            self::YER => '﷼',
            self::ZMW => 'ZK',

        };
    }
}
