<?php

namespace DevFighters\Utils\Domain\Enum;

/**
 * @method static self[] cases()  Retourne tous les cas de l'énumération
 */
enum AppTimezoneEnum: int
{

    case UTC = 1;
    case AFRICA_ABIDJAN = 2;
    case AFRICA_ACCRA = 3;
    case AFRICA_ADDIS_ABABA = 4;
    case AFRICA_ALGIERS = 5;
    case AFRICA_ASMARA = 6;
    case AFRICA_BAMAKO = 7;
    case AFRICA_BANGUI = 8;
    case AFRICA_BANJUL = 9;
    case AFRICA_BISSAU = 10;
    case AFRICA_BLANTYRE = 11;
    case AFRICA_BRAZZAVILLE = 12;
    case AFRICA_BUJUMBURA = 13;
    case AFRICA_CAIRO = 14;
    case AFRICA_CASABLANCA = 15;
    case AFRICA_CEUTA = 16;
    case AFRICA_CONAKRY = 17;
    case AFRICA_DAKAR = 18;
    case AFRICA_DAR_ES_SALAAM = 19;
    case AFRICA_DJIBOUTI = 20;
    case AFRICA_DOUALA = 21;
    case AFRICA_EL_AAIUN = 22;
    case AFRICA_FREETOWN = 23;
    case AFRICA_GABORONE = 24;
    case AFRICA_HARARE = 25;
    case AFRICA_JOHANNESBURG = 26;
    case AFRICA_JUBA = 27;
    case AFRICA_KAMPALA = 28;
    case AFRICA_KHARTOUM = 29;
    case AFRICA_KIGALI = 30;
    case AFRICA_KINSHASA = 31;
    case AFRICA_LAGOS = 32;
    case AFRICA_LIBREVILLE = 33;
    case AFRICA_LOME = 34;
    case AFRICA_LUANDA = 35;
    case AFRICA_LUBUMBASHI = 36;
    case AFRICA_LUSAKA = 37;
    case AFRICA_MALABO = 38;
    case AFRICA_MAPUTO = 39;
    case AFRICA_MASERU = 40;
    case AFRICA_MBABANE = 41;
    case AFRICA_MOGADISHU = 42;
    case AFRICA_MONROVIA = 43;
    case AFRICA_NAIROBI = 44;
    case AFRICA_NDJAMENA = 45;
    case AFRICA_NIAMEY = 46;
    case AFRICA_NOUAKCHOTT = 47;
    case AFRICA_OUAGADOUGOU = 48;
    case AFRICA_PORTO_NOVO = 49;
    case AFRICA_SAO_TOME = 50;
    case AFRICA_TRIPOLI = 51;
    case AFRICA_TUNIS = 52;
    case AFRICA_WINDHOEK = 53;
    case AMERICA_ADAK = 54;
    case AMERICA_ANCHORAGE = 55;
    case AMERICA_ANGUILLA = 56;
    case AMERICA_ANTIGUA = 57;
    case AMERICA_ARAGUAINA = 58;
    case AMERICA_ARGENTINA_BUENOS_AIRES = 59;
    case AMERICA_ARGENTINA_CATAMARCA = 60;
    case AMERICA_ARGENTINA_CORDOBA = 61;
    case AMERICA_ARGENTINA_JUJUY = 62;
    case AMERICA_ARGENTINA_LA_RIOJA = 63;
    case AMERICA_ARGENTINA_MENDOZA = 64;
    case AMERICA_ARGENTINA_RIO_GALLEGOS = 65;
    case AMERICA_ARGENTINA_SALTA = 66;
    case AMERICA_ARGENTINA_SAN_JUAN = 67;
    case AMERICA_ARGENTINA_SAN_LUIS = 68;
    case AMERICA_ARGENTINA_TUCUMAN = 69;
    case AMERICA_ARGENTINA_USHUAIA = 70;
    case AMERICA_ARUBA = 71;
    case AMERICA_ASUNCION = 72;
    case AMERICA_ATIKOKAN = 73;
    case AMERICA_BAHIA = 74;
    case AMERICA_BAHIA_BANDERAS = 75;
    case AMERICA_BARBADOS = 76;
    case AMERICA_BELEM = 77;
    case AMERICA_BELIZE = 78;
    case AMERICA_BLANC_SABLON = 79;
    case AMERICA_BOA_VISTA = 80;
    case AMERICA_BOGOTA = 81;
    case AMERICA_BOISE = 82;
    case AMERICA_CAMBRIDGE_BAY = 83;
    case AMERICA_CAMPO_GRANDE = 84;
    case AMERICA_CANCUN = 85;
    case AMERICA_CARACAS = 86;
    case AMERICA_CAYENNE = 87;
    case AMERICA_CAYMAN = 88;
    case AMERICA_CHICAGO = 89;
    case AMERICA_CHIHUAHUA = 90;
    case AMERICA_CIUDAD_JUAREZ = 91;
    case AMERICA_COSTA_RICA = 92;
    case AMERICA_COYHAIQUE = 420;
    case AMERICA_CRESTON = 93;
    case AMERICA_CUIABA = 94;
    case AMERICA_CURACAO = 95;
    case AMERICA_DANMARKSHAVN = 96;
    case AMERICA_DAWSON = 97;
    case AMERICA_DAWSON_CREEK = 98;
    case AMERICA_DENVER = 99;
    case AMERICA_DETROIT = 100;
    case AMERICA_DOMINICA = 101;
    case AMERICA_EDMONTON = 102;
    case AMERICA_EIRUNEPE = 103;
    case AMERICA_EL_SALVADOR = 104;
    case AMERICA_FORT_NELSON = 105;
    case AMERICA_FORTALEZA = 106;
    case AMERICA_GLACE_BAY = 107;
    case AMERICA_GOOSE_BAY = 108;
    case AMERICA_GRAND_TURK = 109;
    case AMERICA_GRENADA = 110;
    case AMERICA_GUADELOUPE = 111;
    case AMERICA_GUATEMALA = 112;
    case AMERICA_GUAYAQUIL = 113;
    case AMERICA_GUYANA = 114;
    case AMERICA_HALIFAX = 115;
    case AMERICA_HAVANA = 116;
    case AMERICA_HERMOSILLO = 117;
    case AMERICA_INDIANA_INDIANAPOLIS = 118;
    case AMERICA_INDIANA_KNOX = 119;
    case AMERICA_INDIANA_MARENGO = 120;
    case AMERICA_INDIANA_PETERSBURG = 121;
    case AMERICA_INDIANA_TELL_CITY = 122;
    case AMERICA_INDIANA_VEVAY = 123;
    case AMERICA_INDIANA_VINCENNES = 124;
    case AMERICA_INDIANA_WINAMAC = 125;
    case AMERICA_INUVIK = 126;
    case AMERICA_IQALUIT = 127;
    case AMERICA_JAMAICA = 128;
    case AMERICA_JUNEAU = 129;
    case AMERICA_KENTUCKY_LOUISVILLE = 130;
    case AMERICA_KENTUCKY_MONTICELLO = 131;
    case AMERICA_KRALENDIJK = 132;
    case AMERICA_LA_PAZ = 133;
    case AMERICA_LIMA = 134;
    case AMERICA_LOS_ANGELES = 135;
    case AMERICA_LOWER_PRINCES = 136;
    case AMERICA_MACEIO = 137;
    case AMERICA_MANAGUA = 138;
    case AMERICA_MANAUS = 139;
    case AMERICA_MARIGOT = 140;
    case AMERICA_MARTINIQUE = 141;
    case AMERICA_MATAMOROS = 142;
    case AMERICA_MAZATLAN = 143;
    case AMERICA_MENOMINEE = 144;
    case AMERICA_MERIDA = 145;
    case AMERICA_METLAKATLA = 146;
    case AMERICA_MEXICO_CITY = 147;
    case AMERICA_MIQUELON = 148;
    case AMERICA_MONCTON = 149;
    case AMERICA_MONTERREY = 150;
    case AMERICA_MONTEVIDEO = 151;
    case AMERICA_MONTSERRAT = 152;
    case AMERICA_NASSAU = 153;
    case AMERICA_NEW_YORK = 154;
    case AMERICA_NOME = 155;
    case AMERICA_NORONHA = 156;
    case AMERICA_NORTH_DAKOTA_BEULAH = 157;
    case AMERICA_NORTH_DAKOTA_CENTER = 158;
    case AMERICA_NORTH_DAKOTA_NEW_SALEM = 159;
    case AMERICA_NUUK = 160;
    case AMERICA_OJINAGA = 161;
    case AMERICA_PANAMA = 162;
    case AMERICA_PARAMARIBO = 163;
    case AMERICA_PHOENIX = 164;
    case AMERICA_PORT_AU_PRINCE = 165;
    case AMERICA_PORT_OF_SPAIN = 166;
    case AMERICA_PORTO_VELHO = 167;
    case AMERICA_PUERTO_RICO = 168;
    case AMERICA_PUNTA_ARENAS = 169;
    case AMERICA_RANKIN_INLET = 170;
    case AMERICA_RECIFE = 171;
    case AMERICA_REGINA = 172;
    case AMERICA_RESOLUTE = 173;
    case AMERICA_RIO_BRANCO = 174;
    case AMERICA_SANTAREM = 175;
    case AMERICA_SANTIAGO = 176;
    case AMERICA_SANTO_DOMINGO = 177;
    case AMERICA_SAO_PAULO = 178;
    case AMERICA_SCORESBYSUND = 179;
    case AMERICA_SITKA = 180;
    case AMERICA_ST_BARTHELEMY = 181;
    case AMERICA_ST_JOHNS = 182;
    case AMERICA_ST_KITTS = 183;
    case AMERICA_ST_LUCIA = 184;
    case AMERICA_ST_THOMAS = 185;
    case AMERICA_ST_VINCENT = 186;
    case AMERICA_SWIFT_CURRENT = 187;
    case AMERICA_TEGUCIGALPA = 188;
    case AMERICA_THULE = 189;
    case AMERICA_TIJUANA = 190;
    case AMERICA_TORONTO = 191;
    case AMERICA_TORTOLA = 192;
    case AMERICA_VANCOUVER = 193;
    case AMERICA_WHITEHORSE = 194;
    case AMERICA_WINNIPEG = 195;
    case AMERICA_YAKUTAT = 196;
    case ANTARCTICA_CASEY = 197;
    case ANTARCTICA_DAVIS = 198;
    case ANTARCTICA_DUMONTDURVILLE = 199;
    case ANTARCTICA_MACQUARIE = 200;
    case ANTARCTICA_MAWSON = 201;
    case ANTARCTICA_MCMURDO = 202;
    case ANTARCTICA_PALMER = 203;
    case ANTARCTICA_ROTHERA = 204;
    case ANTARCTICA_SYOWA = 205;
    case ANTARCTICA_TROLL = 206;
    case ANTARCTICA_VOSTOK = 207;
    case ARCTIC_LONGYEARBYEN = 208;
    case ASIA_ADEN = 209;
    case ASIA_ALMATY = 210;
    case ASIA_AMMAN = 211;
    case ASIA_ANADYR = 212;
    case ASIA_AQTAU = 213;
    case ASIA_AQTOBE = 214;
    case ASIA_ASHGABAT = 215;
    case ASIA_ATYRAU = 216;
    case ASIA_BAGHDAD = 217;
    case ASIA_BAHRAIN = 218;
    case ASIA_BAKU = 219;
    case ASIA_BANGKOK = 220;
    case ASIA_BARNAUL = 221;
    case ASIA_BEIRUT = 222;
    case ASIA_BISHKEK = 223;
    case ASIA_BRUNEI = 224;
    case ASIA_CHITA = 225;
    case ASIA_COLOMBO = 227;
    case ASIA_DAMASCUS = 228;
    case ASIA_DHAKA = 229;
    case ASIA_DILI = 230;
    case ASIA_DUBAI = 231;
    case ASIA_DUSHANBE = 232;
    case ASIA_FAMAGUSTA = 233;
    case ASIA_GAZA = 234;
    case ASIA_HEBRON = 235;
    case ASIA_HO_CHI_MINH = 236;
    case ASIA_HONG_KONG = 237;
    case ASIA_HOVD = 238;
    case ASIA_IRKUTSK = 239;
    case ASIA_JAKARTA = 240;
    case ASIA_JAYAPURA = 241;
    case ASIA_JERUSALEM = 242;
    case ASIA_KABUL = 243;
    case ASIA_KAMCHATKA = 244;
    case ASIA_KARACHI = 245;
    case ASIA_KATHMANDU = 246;
    case ASIA_KHANDYGA = 247;
    case ASIA_KOLKATA = 248;
    case ASIA_KRASNOYARSK = 249;
    case ASIA_KUALA_LUMPUR = 250;
    case ASIA_KUCHING = 251;
    case ASIA_KUWAIT = 252;
    case ASIA_MACAU = 253;
    case ASIA_MAGADAN = 254;
    case ASIA_MAKASSAR = 255;
    case ASIA_MANILA = 256;
    case ASIA_MUSCAT = 257;
    case ASIA_NICOSIA = 258;
    case ASIA_NOVOKUZNETSK = 259;
    case ASIA_NOVOSIBIRSK = 260;
    case ASIA_OMSK = 261;
    case ASIA_ORAL = 262;
    case ASIA_PHNOM_PENH = 263;
    case ASIA_PONTIANAK = 264;
    case ASIA_PYONGYANG = 265;
    case ASIA_QATAR = 266;
    case ASIA_QOSTANAY = 267;
    case ASIA_QYZYLORDA = 268;
    case ASIA_RIYADH = 269;
    case ASIA_SAKHALIN = 270;
    case ASIA_SAMARKAND = 271;
    case ASIA_SEOUL = 272;
    case ASIA_SHANGHAI = 273;
    case ASIA_SINGAPORE = 274;
    case ASIA_SREDNEKOLYMSK = 275;
    case ASIA_TAIPEI = 276;
    case ASIA_TASHKENT = 277;
    case ASIA_TBILISI = 278;
    case ASIA_TEHRAN = 279;
    case ASIA_THIMPHU = 280;
    case ASIA_TOKYO = 281;
    case ASIA_TOMSK = 282;
    case ASIA_ULAANBAATAR = 283;
    case ASIA_URUMQI = 284;
    case ASIA_UST_NERA = 285;
    case ASIA_VIENTIANE = 286;
    case ASIA_VLADIVOSTOK = 287;
    case ASIA_YAKUTSK = 288;
    case ASIA_YANGON = 289;
    case ASIA_YEKATERINBURG = 290;
    case ASIA_YEREVAN = 291;
    case ATLANTIC_AZORES = 292;
    case ATLANTIC_BERMUDA = 293;
    case ATLANTIC_CANARY = 294;
    case ATLANTIC_CAPE_VERDE = 295;
    case ATLANTIC_FAROE = 296;
    case ATLANTIC_MADEIRA = 297;
    case ATLANTIC_REYKJAVIK = 298;
    case ATLANTIC_SOUTH_GEORGIA = 299;
    case ATLANTIC_ST_HELENA = 300;
    case ATLANTIC_STANLEY = 301;
    case AUSTRALIA_ADELAIDE = 302;
    case AUSTRALIA_BRISBANE = 303;
    case AUSTRALIA_BROKEN_HILL = 304;
    case AUSTRALIA_DARWIN = 305;
    case AUSTRALIA_EUCLA = 306;
    case AUSTRALIA_HOBART = 307;
    case AUSTRALIA_LINDEMAN = 308;
    case AUSTRALIA_LORD_HOWE = 309;
    case AUSTRALIA_MELBOURNE = 310;
    case AUSTRALIA_PERTH = 311;
    case AUSTRALIA_SYDNEY = 312;
    case EUROPE_AMSTERDAM = 313;
    case EUROPE_ANDORRA = 314;
    case EUROPE_ASTRAKHAN = 315;
    case EUROPE_ATHENS = 316;
    case EUROPE_BELGRADE = 317;
    case EUROPE_BERLIN = 318;
    case EUROPE_BRATISLAVA = 319;
    case EUROPE_BRUSSELS = 320;
    case EUROPE_BUCHAREST = 321;
    case EUROPE_BUDAPEST = 322;
    case EUROPE_BUSINGEN = 323;
    case EUROPE_CHISINAU = 324;
    case EUROPE_COPENHAGEN = 325;
    case EUROPE_DUBLIN = 326;
    case EUROPE_GIBRALTAR = 327;
    case EUROPE_GUERNSEY = 328;
    case EUROPE_HELSINKI = 329;
    case EUROPE_ISLE_OF_MAN = 330;
    case EUROPE_ISTANBUL = 331;
    case EUROPE_JERSEY = 332;
    case EUROPE_KALININGRAD = 333;
    case EUROPE_KIROV = 334;
    case EUROPE_KYIV = 335;
    case EUROPE_LISBON = 336;
    case EUROPE_LJUBLJANA = 337;
    case EUROPE_LONDON = 338;
    case EUROPE_LUXEMBOURG = 339;
    case EUROPE_MADRID = 340;
    case EUROPE_MALTA = 341;
    case EUROPE_MARIEHAMN = 342;
    case EUROPE_MINSK = 343;
    case EUROPE_MONACO = 344;
    case EUROPE_MOSCOW = 345;
    case EUROPE_OSLO = 346;
    case EUROPE_PARIS = 347;
    case EUROPE_PODGORICA = 348;
    case EUROPE_PRAGUE = 349;
    case EUROPE_RIGA = 350;
    case EUROPE_ROME = 351;
    case EUROPE_SAMARA = 352;
    case EUROPE_SAN_MARINO = 353;
    case EUROPE_SARAJEVO = 354;
    case EUROPE_SARATOV = 355;
    case EUROPE_SIMFEROPOL = 356;
    case EUROPE_SKOPJE = 357;
    case EUROPE_SOFIA = 358;
    case EUROPE_STOCKHOLM = 359;
    case EUROPE_TALLINN = 360;
    case EUROPE_TIRANE = 361;
    case EUROPE_ULYANOVSK = 362;
    case EUROPE_VADUZ = 363;
    case EUROPE_VATICAN = 364;
    case EUROPE_VIENNA = 365;
    case EUROPE_VILNIUS = 366;
    case EUROPE_VOLGOGRAD = 367;
    case EUROPE_WARSAW = 368;
    case EUROPE_ZAGREB = 369;
    case EUROPE_ZURICH = 370;
    case INDIAN_ANTANANARIVO = 371;
    case INDIAN_CHAGOS = 372;
    case INDIAN_CHRISTMAS = 373;
    case INDIAN_COCOS = 374;
    case INDIAN_COMORO = 375;
    case INDIAN_KERGUELEN = 376;
    case INDIAN_MAHE = 377;
    case INDIAN_MALDIVES = 378;
    case INDIAN_MAURITIUS = 379;
    case INDIAN_MAYOTTE = 380;
    case INDIAN_REUNION = 381;
    case PACIFIC_APIA = 382;
    case PACIFIC_AUCKLAND = 383;
    case PACIFIC_BOUGAINVILLE = 384;
    case PACIFIC_CHATHAM = 385;
    case PACIFIC_CHUUK = 386;
    case PACIFIC_EASTER = 387;
    case PACIFIC_EFATE = 388;
    case PACIFIC_FAKAOFO = 389;
    case PACIFIC_FIJI = 390;
    case PACIFIC_FUNAFUTI = 391;
    case PACIFIC_GALAPAGOS = 392;
    case PACIFIC_GAMBIER = 393;
    case PACIFIC_GUADALCANAL = 394;
    case PACIFIC_GUAM = 395;
    case PACIFIC_HONOLULU = 396;
    case PACIFIC_KANTON = 397;
    case PACIFIC_KIRITIMATI = 398;
    case PACIFIC_KOSRAE = 399;
    case PACIFIC_KWAJALEIN = 400;
    case PACIFIC_MAJURO = 401;
    case PACIFIC_MARQUESAS = 402;
    case PACIFIC_MIDWAY = 403;
    case PACIFIC_NAURU = 404;
    case PACIFIC_NIUE = 405;
    case PACIFIC_NORFOLK = 406;
    case PACIFIC_NOUMEA = 407;
    case PACIFIC_PAGO_PAGO = 408;
    case PACIFIC_PALAU = 409;
    case PACIFIC_PITCAIRN = 410;
    case PACIFIC_POHNPEI = 411;
    case PACIFIC_PORT_MORESBY = 412;
    case PACIFIC_RAROTONGA = 413;
    case PACIFIC_SAIPAN = 414;
    case PACIFIC_TAHITI = 415;
    case PACIFIC_TARAWA = 416;
    case PACIFIC_TONGATAPU = 417;
    case PACIFIC_WAKE = 418;
    case PACIFIC_WALLIS = 419;

    /** Get a human-readable name for the enum case. */
    public function name(): string
    {
        return match ($this) {
            self::UTC => 'UTC',
            self::AFRICA_ABIDJAN => 'Africa/Abidjan',
            self::AFRICA_ACCRA => 'Africa/Accra',
            self::AFRICA_ADDIS_ABABA => 'Africa/Addis_Ababa',
            self::AFRICA_ALGIERS => 'Africa/Algiers',
            self::AFRICA_ASMARA => 'Africa/Asmara',
            self::AFRICA_BAMAKO => 'Africa/Bamako',
            self::AFRICA_BANGUI => 'Africa/Bangui',
            self::AFRICA_BANJUL => 'Africa/Banjul',
            self::AFRICA_BISSAU => 'Africa/Bissau',
            self::AFRICA_BLANTYRE => 'Africa/Blantyre',
            self::AFRICA_BRAZZAVILLE => 'Africa/Brazzaville',
            self::AFRICA_BUJUMBURA => 'Africa/Bujumbura',
            self::AFRICA_CAIRO => 'Africa/Cairo',
            self::AFRICA_CASABLANCA => 'Africa/Casablanca',
            self::AFRICA_CEUTA => 'Africa/Ceuta',
            self::AFRICA_CONAKRY => 'Africa/Conakry',
            self::AFRICA_DAKAR => 'Africa/Dakar',
            self::AFRICA_DAR_ES_SALAAM => 'Africa/Dar_es_Salaam',
            self::AFRICA_DJIBOUTI => 'Africa/Djibouti',
            self::AFRICA_DOUALA => 'Africa/Douala',
            self::AFRICA_EL_AAIUN => 'Africa/El_Aaiun',
            self::AFRICA_FREETOWN => 'Africa/Freetown',
            self::AFRICA_GABORONE => 'Africa/Gaborone',
            self::AFRICA_HARARE => 'Africa/Harare',
            self::AFRICA_JOHANNESBURG => 'Africa/Johannesburg',
            self::AFRICA_JUBA => 'Africa/Juba',
            self::AFRICA_KAMPALA => 'Africa/Kampala',
            self::AFRICA_KHARTOUM => 'Africa/Khartoum',
            self::AFRICA_KIGALI => 'Africa/Kigali',
            self::AFRICA_KINSHASA => 'Africa/Kinshasa',
            self::AFRICA_LAGOS => 'Africa/Lagos',
            self::AFRICA_LIBREVILLE => 'Africa/Libreville',
            self::AFRICA_LOME => 'Africa/Lome',
            self::AFRICA_LUANDA => 'Africa/Luanda',
            self::AFRICA_LUBUMBASHI => 'Africa/Lubumbashi',
            self::AFRICA_LUSAKA => 'Africa/Lusaka',
            self::AFRICA_MALABO => 'Africa/Malabo',
            self::AFRICA_MAPUTO => 'Africa/Maputo',
            self::AFRICA_MASERU => 'Africa/Maseru',
            self::AFRICA_MBABANE => 'Africa/Mbabane',
            self::AFRICA_MOGADISHU => 'Africa/Mogadishu',
            self::AFRICA_MONROVIA => 'Africa/Monrovia',
            self::AFRICA_NAIROBI => 'Africa/Nairobi',
            self::AFRICA_NDJAMENA => 'Africa/Ndjamena',
            self::AFRICA_NIAMEY => 'Africa/Niamey',
            self::AFRICA_NOUAKCHOTT => 'Africa/Nouakchott',
            self::AFRICA_OUAGADOUGOU => 'Africa/Ouagadougou',
            self::AFRICA_PORTO_NOVO => 'Africa/Porto-Novo',
            self::AFRICA_SAO_TOME => 'Africa/Sao_Tome',
            self::AFRICA_TRIPOLI => 'Africa/Tripoli',
            self::AFRICA_TUNIS => 'Africa/Tunis',
            self::AFRICA_WINDHOEK => 'Africa/Windhoek',
            self::AMERICA_ADAK => 'America/Adak',
            self::AMERICA_ANCHORAGE => 'America/Anchorage',
            self::AMERICA_ANGUILLA => 'America/Anguilla',
            self::AMERICA_ANTIGUA => 'America/Antigua',
            self::AMERICA_ARAGUAINA => 'America/Araguaina',
            self::AMERICA_ARGENTINA_BUENOS_AIRES => 'America/Argentina/Buenos_Aires',
            self::AMERICA_ARGENTINA_CATAMARCA => 'America/Argentina/Catamarca',
            self::AMERICA_ARGENTINA_CORDOBA => 'America/Argentina/Cordoba',
            self::AMERICA_ARGENTINA_JUJUY => 'America/Argentina/Jujuy',
            self::AMERICA_ARGENTINA_LA_RIOJA => 'America/Argentina/La_Rioja',
            self::AMERICA_ARGENTINA_MENDOZA => 'America/Argentina/Mendoza',
            self::AMERICA_ARGENTINA_RIO_GALLEGOS => 'America/Argentina/Rio_Gallegos',
            self::AMERICA_ARGENTINA_SALTA => 'America/Argentina/Salta',
            self::AMERICA_ARGENTINA_SAN_JUAN => 'America/Argentina/San_Juan',
            self::AMERICA_ARGENTINA_SAN_LUIS => 'America/Argentina/San_Luis',
            self::AMERICA_ARGENTINA_TUCUMAN => 'America/Argentina/Tucuman',
            self::AMERICA_ARGENTINA_USHUAIA => 'America/Argentina/Ushuaia',
            self::AMERICA_ARUBA => 'America/Aruba',
            self::AMERICA_ASUNCION => 'America/Asuncion',
            self::AMERICA_ATIKOKAN => 'America/Atikokan',
            self::AMERICA_BAHIA => 'America/Bahia',
            self::AMERICA_BAHIA_BANDERAS => 'America/Bahia_Banderas',
            self::AMERICA_BARBADOS => 'America/Barbados',
            self::AMERICA_BELEM => 'America/Belem',
            self::AMERICA_BELIZE => 'America/Belize',
            self::AMERICA_BLANC_SABLON => 'America/Blanc-Sablon',
            self::AMERICA_BOA_VISTA => 'America/Boa_Vista',
            self::AMERICA_BOGOTA => 'America/Bogota',
            self::AMERICA_BOISE => 'America/Boise',
            self::AMERICA_CAMBRIDGE_BAY => 'America/Cambridge_Bay',
            self::AMERICA_CAMPO_GRANDE => 'America/Campo_Grande',
            self::AMERICA_CANCUN => 'America/Cancun',
            self::AMERICA_CARACAS => 'America/Caracas',
            self::AMERICA_CAYENNE => 'America/Cayenne',
            self::AMERICA_CAYMAN => 'America/Cayman',
            self::AMERICA_CHICAGO => 'America/Chicago',
            self::AMERICA_CHIHUAHUA => 'America/Chihuahua',
            self::AMERICA_CIUDAD_JUAREZ => 'America/Ciudad_Juarez',
            self::AMERICA_COSTA_RICA => 'America/Costa_Rica',
            self::AMERICA_COYHAIQUE => 'America/Coyhaique',
            self::AMERICA_CRESTON => 'America/Creston',
            self::AMERICA_CUIABA => 'America/Cuiaba',
            self::AMERICA_CURACAO => 'America/Curacao',
            self::AMERICA_DANMARKSHAVN => 'America/Danmarkshavn',
            self::AMERICA_DAWSON => 'America/Dawson',
            self::AMERICA_DAWSON_CREEK => 'America/Dawson_Creek',
            self::AMERICA_DENVER => 'America/Denver',
            self::AMERICA_DETROIT => 'America/Detroit',
            self::AMERICA_DOMINICA => 'America/Dominica',
            self::AMERICA_EDMONTON => 'America/Edmonton',
            self::AMERICA_EIRUNEPE => 'America/Eirunepe',
            self::AMERICA_EL_SALVADOR => 'America/El_Salvador',
            self::AMERICA_FORT_NELSON => 'America/Fort_Nelson',
            self::AMERICA_FORTALEZA => 'America/Fortaleza',
            self::AMERICA_GLACE_BAY => 'America/Glace_Bay',
            self::AMERICA_GOOSE_BAY => 'America/Goose_Bay',
            self::AMERICA_GRAND_TURK => 'America/Grand_Turk',
            self::AMERICA_GRENADA => 'America/Grenada',
            self::AMERICA_GUADELOUPE => 'America/Guadeloupe',
            self::AMERICA_GUATEMALA => 'America/Guatemala',
            self::AMERICA_GUAYAQUIL => 'America/Guayaquil',
            self::AMERICA_GUYANA => 'America/Guyana',
            self::AMERICA_HALIFAX => 'America/Halifax',
            self::AMERICA_HAVANA => 'America/Havana',
            self::AMERICA_HERMOSILLO => 'America/Hermosillo',
            self::AMERICA_INDIANA_INDIANAPOLIS => 'America/Indiana/Indianapolis',
            self::AMERICA_INDIANA_KNOX => 'America/Indiana/Knox',
            self::AMERICA_INDIANA_MARENGO => 'America/Indiana/Marengo',
            self::AMERICA_INDIANA_PETERSBURG => 'America/Indiana/Petersburg',
            self::AMERICA_INDIANA_TELL_CITY => 'America/Indiana/Tell_City',
            self::AMERICA_INDIANA_VEVAY => 'America/Indiana/Vevay',
            self::AMERICA_INDIANA_VINCENNES => 'America/Indiana/Vincennes',
            self::AMERICA_INDIANA_WINAMAC => 'America/Indiana/Winamac',
            self::AMERICA_INUVIK => 'America/Inuvik',
            self::AMERICA_IQALUIT => 'America/Iqaluit',
            self::AMERICA_JAMAICA => 'America/Jamaica',
            self::AMERICA_JUNEAU => 'America/Juneau',
            self::AMERICA_KENTUCKY_LOUISVILLE => 'America/Kentucky/Louisville',
            self::AMERICA_KENTUCKY_MONTICELLO => 'America/Kentucky/Monticello',
            self::AMERICA_KRALENDIJK => 'America/Kralendijk',
            self::AMERICA_LA_PAZ => 'America/La_Paz',
            self::AMERICA_LIMA => 'America/Lima',
            self::AMERICA_LOS_ANGELES => 'America/Los_Angeles',
            self::AMERICA_LOWER_PRINCES => 'America/Lower_Princes',
            self::AMERICA_MACEIO => 'America/Maceio',
            self::AMERICA_MANAGUA => 'America/Managua',
            self::AMERICA_MANAUS => 'America/Manaus',
            self::AMERICA_MARIGOT => 'America/Marigot',
            self::AMERICA_MARTINIQUE => 'America/Martinique',
            self::AMERICA_MATAMOROS => 'America/Matamoros',
            self::AMERICA_MAZATLAN => 'America/Mazatlan',
            self::AMERICA_MENOMINEE => 'America/Menominee',
            self::AMERICA_MERIDA => 'America/Merida',
            self::AMERICA_METLAKATLA => 'America/Metlakatla',
            self::AMERICA_MEXICO_CITY => 'America/Mexico_City',
            self::AMERICA_MIQUELON => 'America/Miquelon',
            self::AMERICA_MONCTON => 'America/Moncton',
            self::AMERICA_MONTERREY => 'America/Monterrey',
            self::AMERICA_MONTEVIDEO => 'America/Montevideo',
            self::AMERICA_MONTSERRAT => 'America/Montserrat',
            self::AMERICA_NASSAU => 'America/Nassau',
            self::AMERICA_NEW_YORK => 'America/New_York',
            self::AMERICA_NOME => 'America/Nome',
            self::AMERICA_NORONHA => 'America/Noronha',
            self::AMERICA_NORTH_DAKOTA_BEULAH => 'America/North_Dakota/Beulah',
            self::AMERICA_NORTH_DAKOTA_CENTER => 'America/North_Dakota/Center',
            self::AMERICA_NORTH_DAKOTA_NEW_SALEM => 'America/North_Dakota/New_Salem',
            self::AMERICA_NUUK => 'America/Nuuk',
            self::AMERICA_OJINAGA => 'America/Ojinaga',
            self::AMERICA_PANAMA => 'America/Panama',
            self::AMERICA_PARAMARIBO => 'America/Paramaribo',
            self::AMERICA_PHOENIX => 'America/Phoenix',
            self::AMERICA_PORT_AU_PRINCE => 'America/Port-au-Prince',
            self::AMERICA_PORT_OF_SPAIN => 'America/Port_of_Spain',
            self::AMERICA_PORTO_VELHO => 'America/Porto_Velho',
            self::AMERICA_PUERTO_RICO => 'America/Puerto_Rico',
            self::AMERICA_PUNTA_ARENAS => 'America/Punta_Arenas',
            self::AMERICA_RANKIN_INLET => 'America/Rankin_Inlet',
            self::AMERICA_RECIFE => 'America/Recife',
            self::AMERICA_REGINA => 'America/Regina',
            self::AMERICA_RESOLUTE => 'America/Resolute',
            self::AMERICA_RIO_BRANCO => 'America/Rio_Branco',
            self::AMERICA_SANTAREM => 'America/Santarem',
            self::AMERICA_SANTIAGO => 'America/Santiago',
            self::AMERICA_SANTO_DOMINGO => 'America/Santo_Domingo',
            self::AMERICA_SAO_PAULO => 'America/Sao_Paulo',
            self::AMERICA_SCORESBYSUND => 'America/Scoresbysund',
            self::AMERICA_SITKA => 'America/Sitka',
            self::AMERICA_ST_BARTHELEMY => 'America/St_Barthelemy',
            self::AMERICA_ST_JOHNS => 'America/St_Johns',
            self::AMERICA_ST_KITTS => 'America/St_Kitts',
            self::AMERICA_ST_LUCIA => 'America/St_Lucia',
            self::AMERICA_ST_THOMAS => 'America/St_Thomas',
            self::AMERICA_ST_VINCENT => 'America/St_Vincent',
            self::AMERICA_SWIFT_CURRENT => 'America/Swift_Current',
            self::AMERICA_TEGUCIGALPA => 'America/Tegucigalpa',
            self::AMERICA_THULE => 'America/Thule',
            self::AMERICA_TIJUANA => 'America/Tijuana',
            self::AMERICA_TORONTO => 'America/Toronto',
            self::AMERICA_TORTOLA => 'America/Tortola',
            self::AMERICA_VANCOUVER => 'America/Vancouver',
            self::AMERICA_WHITEHORSE => 'America/Whitehorse',
            self::AMERICA_WINNIPEG => 'America/Winnipeg',
            self::AMERICA_YAKUTAT => 'America/Yakutat',
            self::ANTARCTICA_CASEY => 'Antarctica/Casey',
            self::ANTARCTICA_DAVIS => 'Antarctica/Davis',
            self::ANTARCTICA_DUMONTDURVILLE => 'Antarctica/DumontDUrville',
            self::ANTARCTICA_MACQUARIE => 'Antarctica/Macquarie',
            self::ANTARCTICA_MAWSON => 'Antarctica/Mawson',
            self::ANTARCTICA_MCMURDO => 'Antarctica/McMurdo',
            self::ANTARCTICA_PALMER => 'Antarctica/Palmer',
            self::ANTARCTICA_ROTHERA => 'Antarctica/Rothera',
            self::ANTARCTICA_SYOWA => 'Antarctica/Syowa',
            self::ANTARCTICA_TROLL => 'Antarctica/Troll',
            self::ANTARCTICA_VOSTOK => 'Antarctica/Vostok',
            self::ARCTIC_LONGYEARBYEN => 'Arctic/Longyearbyen',
            self::ASIA_ADEN => 'Asia/Aden',
            self::ASIA_ALMATY => 'Asia/Almaty',
            self::ASIA_AMMAN => 'Asia/Amman',
            self::ASIA_ANADYR => 'Asia/Anadyr',
            self::ASIA_AQTAU => 'Asia/Aqtau',
            self::ASIA_AQTOBE => 'Asia/Aqtobe',
            self::ASIA_ASHGABAT => 'Asia/Ashgabat',
            self::ASIA_ATYRAU => 'Asia/Atyrau',
            self::ASIA_BAGHDAD => 'Asia/Baghdad',
            self::ASIA_BAHRAIN => 'Asia/Bahrain',
            self::ASIA_BAKU => 'Asia/Baku',
            self::ASIA_BANGKOK => 'Asia/Bangkok',
            self::ASIA_BARNAUL => 'Asia/Barnaul',
            self::ASIA_BEIRUT => 'Asia/Beirut',
            self::ASIA_BISHKEK => 'Asia/Bishkek',
            self::ASIA_BRUNEI => 'Asia/Brunei',
            self::ASIA_CHITA => 'Asia/Chita',
            self::ASIA_COLOMBO => 'Asia/Colombo',
            self::ASIA_DAMASCUS => 'Asia/Damascus',
            self::ASIA_DHAKA => 'Asia/Dhaka',
            self::ASIA_DILI => 'Asia/Dili',
            self::ASIA_DUBAI => 'Asia/Dubai',
            self::ASIA_DUSHANBE => 'Asia/Dushanbe',
            self::ASIA_FAMAGUSTA => 'Asia/Famagusta',
            self::ASIA_GAZA => 'Asia/Gaza',
            self::ASIA_HEBRON => 'Asia/Hebron',
            self::ASIA_HO_CHI_MINH => 'Asia/Ho_Chi_Minh',
            self::ASIA_HONG_KONG => 'Asia/Hong_Kong',
            self::ASIA_HOVD => 'Asia/Hovd',
            self::ASIA_IRKUTSK => 'Asia/Irkutsk',
            self::ASIA_JAKARTA => 'Asia/Jakarta',
            self::ASIA_JAYAPURA => 'Asia/Jayapura',
            self::ASIA_JERUSALEM => 'Asia/Jerusalem',
            self::ASIA_KABUL => 'Asia/Kabul',
            self::ASIA_KAMCHATKA => 'Asia/Kamchatka',
            self::ASIA_KARACHI => 'Asia/Karachi',
            self::ASIA_KATHMANDU => 'Asia/Kathmandu',
            self::ASIA_KHANDYGA => 'Asia/Khandyga',
            self::ASIA_KOLKATA => 'Asia/Kolkata',
            self::ASIA_KRASNOYARSK => 'Asia/Krasnoyarsk',
            self::ASIA_KUALA_LUMPUR => 'Asia/Kuala_Lumpur',
            self::ASIA_KUCHING => 'Asia/Kuching',
            self::ASIA_KUWAIT => 'Asia/Kuwait',
            self::ASIA_MACAU => 'Asia/Macau',
            self::ASIA_MAGADAN => 'Asia/Magadan',
            self::ASIA_MAKASSAR => 'Asia/Makassar',
            self::ASIA_MANILA => 'Asia/Manila',
            self::ASIA_MUSCAT => 'Asia/Muscat',
            self::ASIA_NICOSIA => 'Asia/Nicosia',
            self::ASIA_NOVOKUZNETSK => 'Asia/Novokuznetsk',
            self::ASIA_NOVOSIBIRSK => 'Asia/Novosibirsk',
            self::ASIA_OMSK => 'Asia/Omsk',
            self::ASIA_ORAL => 'Asia/Oral',
            self::ASIA_PHNOM_PENH => 'Asia/Phnom_Penh',
            self::ASIA_PONTIANAK => 'Asia/Pontianak',
            self::ASIA_PYONGYANG => 'Asia/Pyongyang',
            self::ASIA_QATAR => 'Asia/Qatar',
            self::ASIA_QOSTANAY => 'Asia/Qostanay',
            self::ASIA_QYZYLORDA => 'Asia/Qyzylorda',
            self::ASIA_RIYADH => 'Asia/Riyadh',
            self::ASIA_SAKHALIN => 'Asia/Sakhalin',
            self::ASIA_SAMARKAND => 'Asia/Samarkand',
            self::ASIA_SEOUL => 'Asia/Seoul',
            self::ASIA_SHANGHAI => 'Asia/Shanghai',
            self::ASIA_SINGAPORE => 'Asia/Singapore',
            self::ASIA_SREDNEKOLYMSK => 'Asia/Srednekolymsk',
            self::ASIA_TAIPEI => 'Asia/Taipei',
            self::ASIA_TASHKENT => 'Asia/Tashkent',
            self::ASIA_TBILISI => 'Asia/Tbilisi',
            self::ASIA_TEHRAN => 'Asia/Tehran',
            self::ASIA_THIMPHU => 'Asia/Thimphu',
            self::ASIA_TOKYO => 'Asia/Tokyo',
            self::ASIA_TOMSK => 'Asia/Tomsk',
            self::ASIA_ULAANBAATAR => 'Asia/Ulaanbaatar',
            self::ASIA_URUMQI => 'Asia/Urumqi',
            self::ASIA_UST_NERA => 'Asia/Ust-Nera',
            self::ASIA_VIENTIANE => 'Asia/Vientiane',
            self::ASIA_VLADIVOSTOK => 'Asia/Vladivostok',
            self::ASIA_YAKUTSK => 'Asia/Yakutsk',
            self::ASIA_YANGON => 'Asia/Yangon',
            self::ASIA_YEKATERINBURG => 'Asia/Yekaterinburg',
            self::ASIA_YEREVAN => 'Asia/Yerevan',
            self::ATLANTIC_AZORES => 'Atlantic/Azores',
            self::ATLANTIC_BERMUDA => 'Atlantic/Bermuda',
            self::ATLANTIC_CANARY => 'Atlantic/Canary',
            self::ATLANTIC_CAPE_VERDE => 'Atlantic/Cape_Verde',
            self::ATLANTIC_FAROE => 'Atlantic/Faroe',
            self::ATLANTIC_MADEIRA => 'Atlantic/Madeira',
            self::ATLANTIC_REYKJAVIK => 'Atlantic/Reykjavik',
            self::ATLANTIC_SOUTH_GEORGIA => 'Atlantic/South_Georgia',
            self::ATLANTIC_ST_HELENA => 'Atlantic/St_Helena',
            self::ATLANTIC_STANLEY => 'Atlantic/Stanley',
            self::AUSTRALIA_ADELAIDE => 'Australia/Adelaide',
            self::AUSTRALIA_BRISBANE => 'Australia/Brisbane',
            self::AUSTRALIA_BROKEN_HILL => 'Australia/Broken_Hill',
            self::AUSTRALIA_DARWIN => 'Australia/Darwin',
            self::AUSTRALIA_EUCLA => 'Australia/Eucla',
            self::AUSTRALIA_HOBART => 'Australia/Hobart',
            self::AUSTRALIA_LINDEMAN => 'Australia/Lindeman',
            self::AUSTRALIA_LORD_HOWE => 'Australia/Lord_Howe',
            self::AUSTRALIA_MELBOURNE => 'Australia/Melbourne',
            self::AUSTRALIA_PERTH => 'Australia/Perth',
            self::AUSTRALIA_SYDNEY => 'Australia/Sydney',
            self::EUROPE_AMSTERDAM => 'Europe/Amsterdam',
            self::EUROPE_ANDORRA => 'Europe/Andorra',
            self::EUROPE_ASTRAKHAN => 'Europe/Astrakhan',
            self::EUROPE_ATHENS => 'Europe/Athens',
            self::EUROPE_BELGRADE => 'Europe/Belgrade',
            self::EUROPE_BERLIN => 'Europe/Berlin',
            self::EUROPE_BRATISLAVA => 'Europe/Bratislava',
            self::EUROPE_BRUSSELS => 'Europe/Brussels',
            self::EUROPE_BUCHAREST => 'Europe/Bucharest',
            self::EUROPE_BUDAPEST => 'Europe/Budapest',
            self::EUROPE_BUSINGEN => 'Europe/Busingen',
            self::EUROPE_CHISINAU => 'Europe/Chisinau',
            self::EUROPE_COPENHAGEN => 'Europe/Copenhagen',
            self::EUROPE_DUBLIN => 'Europe/Dublin',
            self::EUROPE_GIBRALTAR => 'Europe/Gibraltar',
            self::EUROPE_GUERNSEY => 'Europe/Guernsey',
            self::EUROPE_HELSINKI => 'Europe/Helsinki',
            self::EUROPE_ISLE_OF_MAN => 'Europe/Isle_of_Man',
            self::EUROPE_ISTANBUL => 'Europe/Istanbul',
            self::EUROPE_JERSEY => 'Europe/Jersey',
            self::EUROPE_KALININGRAD => 'Europe/Kaliningrad',
            self::EUROPE_KIROV => 'Europe/Kirov',
            self::EUROPE_KYIV => 'Europe/Kyiv',
            self::EUROPE_LISBON => 'Europe/Lisbon',
            self::EUROPE_LJUBLJANA => 'Europe/Ljubljana',
            self::EUROPE_LONDON => 'Europe/London',
            self::EUROPE_LUXEMBOURG => 'Europe/Luxembourg',
            self::EUROPE_MADRID => 'Europe/Madrid',
            self::EUROPE_MALTA => 'Europe/Malta',
            self::EUROPE_MARIEHAMN => 'Europe/Mariehamn',
            self::EUROPE_MINSK => 'Europe/Minsk',
            self::EUROPE_MONACO => 'Europe/Monaco',
            self::EUROPE_MOSCOW => 'Europe/Moscow',
            self::EUROPE_OSLO => 'Europe/Oslo',
            self::EUROPE_PARIS => 'Europe/Paris',
            self::EUROPE_PODGORICA => 'Europe/Podgorica',
            self::EUROPE_PRAGUE => 'Europe/Prague',
            self::EUROPE_RIGA => 'Europe/Riga',
            self::EUROPE_ROME => 'Europe/Rome',
            self::EUROPE_SAMARA => 'Europe/Samara',
            self::EUROPE_SAN_MARINO => 'Europe/San_Marino',
            self::EUROPE_SARAJEVO => 'Europe/Sarajevo',
            self::EUROPE_SARATOV => 'Europe/Saratov',
            self::EUROPE_SIMFEROPOL => 'Europe/Simferopol',
            self::EUROPE_SKOPJE => 'Europe/Skopje',
            self::EUROPE_SOFIA => 'Europe/Sofia',
            self::EUROPE_STOCKHOLM => 'Europe/Stockholm',
            self::EUROPE_TALLINN => 'Europe/Tallinn',
            self::EUROPE_TIRANE => 'Europe/Tirane',
            self::EUROPE_ULYANOVSK => 'Europe/Ulyanovsk',
            self::EUROPE_VADUZ => 'Europe/Vaduz',
            self::EUROPE_VATICAN => 'Europe/Vatican',
            self::EUROPE_VIENNA => 'Europe/Vienna',
            self::EUROPE_VILNIUS => 'Europe/Vilnius',
            self::EUROPE_VOLGOGRAD => 'Europe/Volgograd',
            self::EUROPE_WARSAW => 'Europe/Warsaw',
            self::EUROPE_ZAGREB => 'Europe/Zagreb',
            self::EUROPE_ZURICH => 'Europe/Zurich',
            self::INDIAN_ANTANANARIVO => 'Indian/Antananarivo',
            self::INDIAN_CHAGOS => 'Indian/Chagos',
            self::INDIAN_CHRISTMAS => 'Indian/Christmas',
            self::INDIAN_COCOS => 'Indian/Cocos',
            self::INDIAN_COMORO => 'Indian/Comoro',
            self::INDIAN_KERGUELEN => 'Indian/Kerguelen',
            self::INDIAN_MAHE => 'Indian/Mahe',
            self::INDIAN_MALDIVES => 'Indian/Maldives',
            self::INDIAN_MAURITIUS => 'Indian/Mauritius',
            self::INDIAN_MAYOTTE => 'Indian/Mayotte',
            self::INDIAN_REUNION => 'Indian/Reunion',
            self::PACIFIC_APIA => 'Pacific/Apia',
            self::PACIFIC_AUCKLAND => 'Pacific/Auckland',
            self::PACIFIC_BOUGAINVILLE => 'Pacific/Bougainville',
            self::PACIFIC_CHATHAM => 'Pacific/Chatham',
            self::PACIFIC_CHUUK => 'Pacific/Chuuk',
            self::PACIFIC_EASTER => 'Pacific/Easter',
            self::PACIFIC_EFATE => 'Pacific/Efate',
            self::PACIFIC_FAKAOFO => 'Pacific/Fakaofo',
            self::PACIFIC_FIJI => 'Pacific/Fiji',
            self::PACIFIC_FUNAFUTI => 'Pacific/Funafuti',
            self::PACIFIC_GALAPAGOS => 'Pacific/Galapagos',
            self::PACIFIC_GAMBIER => 'Pacific/Gambier',
            self::PACIFIC_GUADALCANAL => 'Pacific/Guadalcanal',
            self::PACIFIC_GUAM => 'Pacific/Guam',
            self::PACIFIC_HONOLULU => 'Pacific/Honolulu',
            self::PACIFIC_KANTON => 'Pacific/Kanton',
            self::PACIFIC_KIRITIMATI => 'Pacific/Kiritimati',
            self::PACIFIC_KOSRAE => 'Pacific/Kosrae',
            self::PACIFIC_KWAJALEIN => 'Pacific/Kwajalein',
            self::PACIFIC_MAJURO => 'Pacific/Majuro',
            self::PACIFIC_MARQUESAS => 'Pacific/Marquesas',
            self::PACIFIC_MIDWAY => 'Pacific/Midway',
            self::PACIFIC_NAURU => 'Pacific/Nauru',
            self::PACIFIC_NIUE => 'Pacific/Niue',
            self::PACIFIC_NORFOLK => 'Pacific/Norfolk',
            self::PACIFIC_NOUMEA => 'Pacific/Noumea',
            self::PACIFIC_PAGO_PAGO => 'Pacific/Pago_Pago',
            self::PACIFIC_PALAU => 'Pacific/Palau',
            self::PACIFIC_PITCAIRN => 'Pacific/Pitcairn',
            self::PACIFIC_POHNPEI => 'Pacific/Pohnpei',
            self::PACIFIC_PORT_MORESBY => 'Pacific/Port_Moresby',
            self::PACIFIC_RAROTONGA => 'Pacific/Rarotonga',
            self::PACIFIC_SAIPAN => 'Pacific/Saipan',
            self::PACIFIC_TAHITI => 'Pacific/Tahiti',
            self::PACIFIC_TARAWA => 'Pacific/Tarawa',
            self::PACIFIC_TONGATAPU => 'Pacific/Tongatapu',
            self::PACIFIC_WAKE => 'Pacific/Wake',
            self::PACIFIC_WALLIS => 'Pacific/Wallis',
        };
    }

}
